### ISSUE TITLE
Update for Blender 4.0

### ISSUE THREAD

**Issue by ma7t3** [Road-hog123/Blender-OMSI-Exporter#15]
## The problem
I installed that plug-in on the current blender version (4.0.0.), but, Wehen I try to export something I always get a script error

## The current workflow
I need to copy my work to an older blender version and export it from there

## The solution
Support of the newer blender versions

**Comment by Road-hog123** [comment]
Stuck a bandaid on my dev branch, hopefully this works for you: [blender-omsi-exporter_dev-4.0.zip](https://github.com/Road-hog123/Blender-OMSI-Exporter/files/13596353/blender-omsi-exporter_dev-4.0.zip)

**Comment by ma7t3** [comment]
I'll try, thank you so much!

**Comment by ma7t3** [comment]
In principle, it works. However, all objects now light up. I had a look at the o3d file, these 12 bits (3 float32 values) should be "0", but here it is "500" in decimal form.
![image](https://github.com/Road-hog123/Blender-OMSI-Exporter/assets/104677051/4a89ce59-5a59-4a0f-9e21-31056ba02e88)

**Comment by Road-hog123** [comment]
The bandaid redirected "Emission" to "Emission Color"—"Emission Strength" is not considered. You will have to change "Emission Color" to pure black (from its default of pure white), even if "Emission Strength" is set to zero, until I address this properly in a proper release.
