### ISSUE TITLE
Installation Fail

### ISSUE THREAD

**Issue by KCR58Game** [Road-hog123/Blender-OMSI-Exporter#16]
I use Blender 3.6 
I downloaded and install the .zip but nothing is actually installed
I don't have any other o3d import-export addon at this moment
Any idea? Thank you

**Comment by Road-hog123** [comment]
@KCR58Game I can't reproduce this—are you sure you're enabling the addon after installing it?

**Comment by KCR58Game** [comment]
> @KCR58Game I can't reproduce this—are you sure you're enabling the addon after installing it?

The problem is, nothing installed, I can't even have the addon to tick enabling it.

**Comment by Road-hog123** [comment]
> I downloaded and install the .zip

Which .zip did you download?

**Comment by KCR58Game** [comment]
> > I downloaded and install the .zip
> 
> Which .zip did you download?

Green icon [< > Code] , and download zip. 
I install that .zip without doing anything, no unzip or whatever.

**Comment by Road-hog123** [comment]
Ah, that explains it! The instructions say to download from the [releases page](https://github.com/Road-hog123/blender-omsi-exporter/releases/) - GitHub's source download encapsulates the repository in another folder, which breaks Blender's addon discovery. Manually copying the `io_export_o3d` folder up a level into `addons` should cause it to show up in the addons list.
