### ISSUE TITLE
Initialise filename with object name, not blend file name

### ISSUE THREAD

**Issue by ZaneThurston** [Road-hog123/Blender-OMSI-Exporter#2]
A little suggestion: In exporting, get the blender name of the selected 3D object placed on filename textbox. It's a little feature that agilize the workflow exporting many objects in sequence.

**Comment by Road-hog123** [comment]
Thank you for your suggestion!

I agree that it would accelerate that workflow, but I would encourage you to look into the [Automation](https://github.com/Road-hog123/Blender-OMSI-Exporter#automating-with-python-scripts) section in the documention for an alternative workflow for files with a lot of export operations. With a little setup, exporting many objects in sequence can become just a couple of clicks.

If you have any feedback about the implementation and/or documention of the automation feature, I would welcome it - it may still be beneficial to many users to add features like this to accelerate laborious but programming-free workflows, even if they duplicate functionality available through custom Python scripts.

**Comment by Road-hog123** [comment]
Given there's interest in this feature from at least 3 people, I'm reopening this with a view to implement this change.
