### ISSUE TITLE
Missing textures when exporting

### ISSUE THREAD

**Issue by Oyan244** [Road-hog123/Blender-OMSI-Exporter#5]
## Bug Description
After exporting and then cheking the model file itself, each material slot became a "." rather than the texture filename itself. It happens for 99% of my files when I export, but it fine for some other models. When the model is loaded into the game it becomes white (as there is no texture named ".") Had tried this even with Blender v2.93 LTS and 3.00, still same problem. Currently running on Blender 3.2.

## Steps to Reproduce
I had just exported my models with the default setiings, I did not tweak any of the options. Even I changed some options, the result is still the same.

## Version Information
 - Blender: v3.2
 - Exporter: v3.0.1

![image](https://user-images.githubusercontent.com/20854300/175862875-e4549a9e-e049-4055-9773-bec5bf027c20.png)

**Comment by Road-hog123** [comment]
Would you be prepared to attach a .blend file that exhibits this issue? Can be as simple as a cube and you don't have to include any texture files.

If you're not prepared to share one publicly, my email should be linked in my GitHub profile.

**Comment by Oyan244** [comment]
I'll attath a screencast of how I exported here, hope you find this helpful. If you still would like a .blend file then please do tell me.

https://user-images.githubusercontent.com/20854300/176083842-909b9e04-0246-443b-95d1-b86f36eb3c54.mp4

**Comment by Road-hog123** [comment]
The main information I wanted to get from a .blend file is your material setup and particularly the texture paths. The exporter is either not finding the texture node or is garbling the path enroute to the file.

**Comment by Oyan244** [comment]
Sure, I'll email you my blender file then.
