### ISSUE TITLE
SyntaxError when enabling on Blender 2.79

### ISSUE THREAD

**Issue by FanJinJin** [Road-hog123/Blender-OMSI-Exporter#6]
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.79b\2.79\scripts\modules\addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "C:\Users\Ho Wai\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_export_o3d\__init__.py", line 67
    filepath: StringProperty(subtype='FILE_PATH')
            ^
SyntaxError: invalid syntax
```

Blender:2.79

**Comment by Road-hog123** [comment]
This addon cannot be used with Blender 2.79. Please upgrade to a supported Blender version (2.93 LTS or 3.2) to use this addon.

**Comment by FanJinJin** [comment]
Now i am using 3.22 it only can export

「Road-hog123 ***@***.***>」在 2022年8月16日 週二，下午8:50 寫道：

**Comment by Road-hog123** [comment]
Yes? Did you expect anything else from **Blender-OMSI-Exporter**?

**Comment by FanJinJin** [comment]
How about to import it

「Road-hog123 ***@***.***>」在 2022年8月20日 週六，上午1:04 寫道：

**Comment by Road-hog123** [comment]
No, in case the name of the addon or the README weren't clear: this is an exporter - its only function is to export from Blender to OMSI.

You are more than welcome to create a Feature Request issue if you can come up with a good reason to import O3D files that isn't the creation of unauthorised modifications of existing OMSI content.
