### ISSUE TITLE
Auto-append `.o3d` extension if filename is typed without it

### ISSUE THREAD

**Issue by jem-suu** [Road-hog123/Blender-OMSI-Exporter#7]
Currently, if a filename is typed out (replacing the auto generated one) and if the `.o3d` file extension is forgotten, it generates a file with no extension as the save dialog does not auto-complete the filename. 

Other exporters _(quickly tested with the COLLADA exporter)_ append the extension once the name is set, so possibly adding this functionality could be a minor, but nice, quality of life improvement.

_(Upon a bit of digging, I've put this as an enhancement rather than a bug as I'm not sure if it was intentionally scripted or something to do with Blender 3.0 messing up the plugin again)_

**Comment by Road-hog123** [comment]
Can you confirm that an O3D file with no suffix does not work in OMSI?
